// Data extracted from user PDFs and OCR
export interface WordDef {
  word: string;
  type: string;
  level: string;
  translation?: string;
}

export const realWords: WordDef[] = [
  // Existing B2/C1 Selection
  { word: "absorb", type: "v.", level: "B2" },
  { word: "accommodation", type: "n.", level: "B2" },
  { word: "accomplish", type: "v.", level: "B2" },
  { word: "adequate", type: "adj.", level: "B2" },
  { word: "ambitious", type: "adj.", level: "B2" },
  { word: "anticipate", type: "v.", level: "B2" },
  { word: "appropriate", type: "adj.", level: "B2" },
  { word: "assistance", type: "n.", level: "B2" },
  { word: "beneficial", type: "adj.", level: "B2" },
  { word: "capability", type: "n.", level: "C1" },
  { word: "circumstance", type: "n.", level: "B2" },
  { word: "comprehensive", type: "adj.", level: "B2" },
  { word: "conscientious", type: "adj.", level: "C1" },
  { word: "controversial", type: "adj.", level: "B2" },
  { word: "curriculum", type: "n.", level: "B2" },
  { word: "deficiency", type: "n.", level: "C1" },
  { word: "demonstrate", type: "v.", level: "B2" },
  { word: "depression", type: "n.", level: "B2" },
  { word: "differentiate", type: "v.", level: "C1" },
  { word: "disastrous", type: "adj.", level: "C1" },
  { word: "distinguish", type: "v.", level: "B2" },
  { word: "elaborate", type: "adj.", level: "C1" },
  { word: "embarrassment", type: "n.", level: "C1" },
  { word: "enthusiastic", type: "adj.", level: "B2" },
  { word: "entrepreneur", type: "n.", level: "B2" },
  { word: "equivalent", type: "adj.", level: "B2" },
  { word: "evaluate", type: "v.", level: "B2" },
  { word: "exaggerate", type: "v.", level: "C1" },
  { word: "extraordinary", type: "adj.", level: "B2" },
  { word: "fascinating", type: "adj.", level: "B2" },
  { word: "fluctuation", type: "n.", level: "C1" },
  { word: "fundamental", type: "adj.", level: "B2" },
  { word: "genuine", type: "adj.", level: "B2" },
  { word: "guarantee", type: "n/v", level: "B2" },
  { word: "hierarchy", type: "n.", level: "C1" },
  { word: "hypothesis", type: "n.", level: "B2" },
  { word: "identical", type: "adj.", level: "B2" },
  { word: "implement", type: "v.", level: "B2" },
  { word: "indigenous", type: "adj.", level: "C1" },
  { word: "inevitable", type: "adj.", level: "B2" },
  { word: "infrastructure", type: "n.", level: "B2" },
  { word: "initiative", type: "n.", level: "B2" },
  { word: "integration", type: "n.", level: "C1" },
  { word: "interpretation", type: "n.", level: "B2" },
  { word: "intervention", type: "n.", level: "C1" },
  { word: "investigation", type: "n.", level: "B2" },
  { word: "justification", type: "n.", level: "C1" },
  { word: "legislation", type: "n.", level: "C1" },
  { word: "maintenance", type: "n.", level: "C1" },
  { word: "manufacture", type: "v.", level: "B2" },
  { word: "mechanism", type: "n.", level: "B2" },
  { word: "negotiation", type: "n.", level: "B2" },
  { word: "nevertheless", type: "adv.", level: "B2" },
  { word: "observation", type: "n.", level: "B2" },
  { word: "opportunity", type: "n.", level: "B2" },
  { word: "parliament", type: "n.", level: "C1" },
  { word: "participant", type: "n.", level: "B2" },
  { word: "perception", type: "n.", level: "B2" },
  { word: "permanent", type: "adj.", level: "B2" },
  { word: "phenomenon", type: "n.", level: "B2" },
  { word: "philosophy", type: "n.", level: "B2" },
  { word: "practitioner", type: "n.", level: "C1" },
  { word: "preliminary", type: "adj.", level: "C1" },
  { word: "preparation", type: "n.", level: "B2" },
  { word: "prescription", type: "n.", level: "C1" },
  { word: "privilege", type: "n.", level: "C1" },
  { word: "probability", type: "n.", level: "B2" },
  { word: "professional", type: "adj.", level: "B2" },
  { word: "psychological", type: "adj.", level: "B2" },
  { word: "questionnaire", type: "n.", level: "B2" },
  { word: "recommendation", type: "n.", level: "B2" },
  { word: "rehabilitation", type: "n.", level: "C1" },
  { word: "reinforce", type: "v.", level: "B2" },
  { word: "reliable", type: "adj.", level: "B2" },
  { word: "representative", type: "n.", level: "B2" },
  { word: "requirement", type: "n.", level: "B2" },
  { word: "sophisticated", type: "adj.", level: "B2" },
  { word: "specification", type: "n.", level: "C1" },
  { word: "spectacular", type: "adj.", level: "B2" },
  { word: "straightforward", type: "adj.", level: "C1" },
  { word: "substantially", type: "adv.", level: "C1" },
  { word: "sustainable", type: "adj.", level: "B2" },
  { word: "theoretical", type: "adj.", level: "C1" },
  { word: "transformation", type: "n.", level: "B2" },
  { word: "transportation", type: "n.", level: "B2" },
  { word: "unprecedented", type: "adj.", level: "C1" },
  { word: "vulnerable", type: "adj.", level: "C1" },
  { word: "widespread", type: "adj.", level: "B2" },
  // Newly Added DET High-Utility Words
  { word: "acquire", type: "v.", level: "B2" },
  { word: "alternative", type: "n/adj", level: "B2" },
  { word: "analyze", type: "v.", level: "B2" },
  { word: "approach", type: "n/v", level: "B2" },
  { word: "aspect", type: "n.", level: "B2" },
  { word: "assess", type: "v.", level: "B2" },
  { word: "assume", type: "v.", level: "B2" },
  { word: "authority", type: "n.", level: "B2" },
  { word: "available", type: "adj.", level: "B2" },
  { word: "benefit", type: "n/v", level: "B2" },
  { word: "concept", type: "n.", level: "B2" },
  { word: "consist", type: "v.", level: "B2" },
  { word: "constitute", type: "v.", level: "C1" },
  { word: "context", type: "n.", level: "B2" },
  { word: "create", type: "v.", level: "A2" }, // Common but vital
  { word: "data", type: "n.", level: "B2" },
  { word: "define", type: "v.", level: "B2" },
  { word: "derive", type: "v.", level: "B2" },
  { word: "distribute", type: "v.", level: "B2" },
  { word: "economy", type: "n.", level: "B2" },
  { word: "environment", type: "n.", level: "B1" },
  { word: "establish", type: "v.", level: "B2" },
  { word: "estimate", type: "v.", level: "B2" },
  { word: "factor", type: "n.", level: "B2" },
  { word: "finance", type: "n.", level: "B2" },
  { word: "formula", type: "n.", level: "C1" },
  { word: "function", type: "n/v", level: "B2" },
  { word: "identify", type: "v.", level: "B2" },
  { word: "income", type: "n.", level: "B2" },
  { word: "indicate", type: "v.", level: "B2" },
  { word: "individual", type: "n/adj", level: "B2" },
  { word: "involve", type: "v.", level: "B2" },
  { word: "issue", type: "n.", level: "B2" },
  { word: "labor", type: "n.", level: "C1" },
  { word: "legal", type: "adj.", level: "B2" },
  { word: "major", type: "adj.", level: "B2" },
  { word: "method", type: "n.", level: "B2" },
  { word: "occur", type: "v.", level: "B2" },
  { word: "percent", type: "n.", level: "B2" },
  { word: "period", type: "n.", level: "B2" },
  { word: "policy", type: "n.", level: "B2" },
  { word: "principle", type: "n.", level: "C1" },
  { word: "procedure", type: "n.", level: "B2" },
  { word: "process", type: "n.", level: "B2" },
  { word: "required", type: "adj.", level: "B2" },
  { word: "research", type: "n.", level: "B2" },
  { word: "response", type: "n.", level: "B2" },
  { word: "role", type: "n.", level: "B2" },
  { word: "section", type: "n.", level: "B2" },
  { word: "sector", type: "n.", level: "C1" },
  { word: "significant", type: "adj.", level: "B2" },
  { word: "similar", type: "adj.", level: "B1" },
  { word: "source", type: "n.", level: "B2" },
  { word: "specific", type: "adj.", level: "B2" },
  { word: "structure", type: "n.", level: "B2" },
  { word: "theory", type: "n.", level: "B2" },
  { word: "vary", type: "v.", level: "B2" }
];

// Pseudo-words: Structurally correct English morphology but meaningless
export const fakeWords: string[] = [
  "braliance", "compoltion", "defract", "elusivity", "flumptious", 
  "glamerate", "histeric", "intervost", "juridiction", "klonder", 
  "luminent", "mignify", "noctulance", "obliverate", "plender", 
  "quantious", "replind", "scrampt", "tempolary", "unbrive", 
  "veridicality", "wimbley", "xylophate", "yorbid", "zandor",
  "transvade", "sublimate", "prelaption", "conferance", "depolish",
  "ambulate", "fravolous", "glandure", "harvical", "instep",
  "jesture", "klimber", "loptious", "marvelousness", "naptual",
  "opturate", "proform", "qualifyer", "rantify", "splune",
  "trundle", "ubilance", "vendure", "westral", "yonderly",
  "blandishment", "crunkle", "dorp", "frill", "gorp",
  "harkle", "jibber", "kempt", "larkle", "mimp",
  "nark", "piffle", "quib", "rort", "snark",
  "thrum", "umber", "vorp", "wiffle", "yarble",
  "abstrusion", "beleaguerment", "circumvade", "disgrunt", "enfeeblement",
  "flabbergastation", "grandiloquence", "hippopotomonstrosesquippedaliophobia", "interfenestration", "juxtapositionality",
  "kerfuffle", "lugubriosity", "magniloquence", "obfuscation", "perspicacity",
  "quixotism", "recalcitrance", "sesquipedalianism", "tintinnabulation", "ubiquity",
  "verisimilitude", "weltschmerz", "xenophobia", "zeitgeist", "abjuration",
  "bloviate", "crapulent", "defenestrate", "epistemology", "fatuous",
  "gerrymander", "hegemony", "iconoclast", "jingoism", "kitsch",
  "laconic", "maudlin", "nefarious", "obsequious", "panacea",
  "quixotic", "redoubtable", "sycophant", "truculent", "ululate"
];

export const transitionWords = [
  { word: "Furthermore", level: "B2/C1", meaning: "De plus, En outre", usage: "Addition" },
  { word: "Moreover", level: "B2/C1", meaning: "De plus, Qui plus est", usage: "Addition" },
  { word: "Conversely", level: "B2/C1", meaning: "Inversement", usage: "Contrast" },
  { word: "Nevertheless", level: "B2/C1", meaning: "Néanmoins", usage: "Contrast" },
  { word: "Specifically", level: "C1", meaning: "Spécifiquement", usage: "Explication" },
  { word: "Consequently", level: "B2/C1", meaning: "Par conséquent", usage: "Result" },
  { word: "Ultimately", level: "B2/C1", meaning: "Finalement", usage: "Conclusion" },
  { word: "Admittedly", level: "B2", meaning: "Certes", usage: "Concession" },
  { word: "Notwithstanding", level: "C1", meaning: "Malgré cela", usage: "Contrast" },
  { word: "However", level: "B1", meaning: "Cependant", usage: "Contrast" },
  { word: "Therefore", level: "B1", meaning: "Donc", usage: "Result" },
  { word: "In addition", level: "B1", meaning: "De plus", usage: "Addition" },
  { word: "For instance", level: "B1", meaning: "Par exemple", usage: "Example" },
  { word: "On the other hand", level: "B2", meaning: "D'autre part", usage: "Contrast" },
  { word: "In conclusion", level: "B1", meaning: "En conclusion", usage: "Conclusion" }
];

export const photoVocab = {
  general: ["In the foreground", "In the background", "At the center", "Bird's-eye view", "A close-up"],
  action: ["Strolling", "Conversing", "Pondering", "Gazing at", "Commuting"],
  atmosphere: ["Bustling", "Serene", "Chaotic", "Vibrant", "Somber"],
  speculation: ["It seems as though...", "I would assume that...", "The image conveys a sense of...", "This might symbolize..."]
};

// Structured list for Flashcards
export const photoWords: WordDef[] = [
    { word: "Foreground", type: "n.", level: "B1" },
    { word: "Background", type: "n.", level: "B1" },
    { word: "Strolling", type: "v.", level: "B2" },
    { word: "Bustling", type: "adj.", level: "C1" },
    { word: "Serene", type: "adj.", level: "C1" },
    { word: "Chaotic", type: "adj.", level: "B2" },
    { word: "Vibrant", type: "adj.", level: "B2" },
    { word: "Somber", type: "adj.", level: "C1" },
    { word: "Pondering", type: "v.", level: "C1" },
    { word: "Gazing", type: "v.", level: "B2" },
    { word: "Commuting", type: "v.", level: "B2" },
    { word: "Pedestrian", type: "n.", level: "B2" },
    { word: "Skyscraper", type: "n.", level: "B1" },
    { word: "Rural", type: "adj.", level: "B2" },
    { word: "Urban", type: "adj.", level: "B2" },
    { word: "Landscape", type: "n.", level: "B1" },
    { word: "Portrait", type: "n.", level: "B1" },
    { word: "Atmosphere", type: "n.", level: "B2" },
    { word: "Distinct", type: "adj.", level: "B2" },
    { word: "Vivid", type: "adj.", level: "B2" }
];

// Unified type for handling all word lists in flashcards
export const transitionWordsList: WordDef[] = transitionWords.map(t => ({
    word: t.word,
    type: "adv.",
    level: t.level,
    translation: t.meaning // Pre-filled translation for these
}));


export const photoMethod = [
  { step: 1, name: "Introduction", detail: "Identify location & main subject (5-10s)", example: "This picture appears to be a busy city scene." },
  { step: 2, name: "Foreground/Key Details", detail: "Describe main people/actions (20-30s)", example: "In the foreground, a young woman is leaning against a bicycle." },
  { step: 3, name: "Background/Context", detail: "Describe setting/atmosphere (20-30s)", example: "Furthermore, in the background, the buildings are illuminated by the afternoon sun." },
  { step: 4, name: "Speculation/Conclusion", detail: "Guess feelings/reasons (10-15s)", example: "The image conveys a sense of urban life. I would assume it's rush hour." }
];

export const studyPlan = [
  { day: 1, topic: "Vocabulaire B2 (Nouns/Verbs)", activity: "Flashcards & Real Word Game" },
  { day: 2, topic: "Description Photo (Structure)", activity: "Write About Photo Practice" },
  { day: 3, topic: "Mots de Transition & Spelling", activity: "Fill in the Blank & Spelling Drill" },
  { day: 4, topic: "Vocabulaire C1 (Abstract)", activity: "Flashcards & Context Sentences" },
  { day: 5, topic: "Dictée & Orthographe", activity: "Fill in the Blanks (Dysorthography Focus)" },
  { day: 6, topic: "Speaking (Describe Photo)", activity: "Oral Simulation (Self-Timed)" },
  { day: 7, topic: "Review Week 1", activity: "Full Mix Game" },
  { day: 8, topic: "Advanced Connectors", activity: "Fill in the Blank with Transition Words" },
  { day: 9, topic: "Speed Reading", activity: "Real Word Game (Speed Mode)" },
  { day: 10, topic: "Complex Sentences", activity: "Write About Photo (Hard Mode)" },
  { day: 11, topic: "Synonyms & Paraphrasing", activity: "Gemini Rewrite Tool" },
  { day: 12, topic: "Final Vocab Polish", activity: "Flashcards (Only Hard Words)" },
  { day: 13, topic: "Full Simulation Part 1", activity: "All Games" },
  { day: 14, topic: "Full Simulation Part 2", activity: "Relax & Confidence" },
];